### ISSUE TITLE
顧客ID (CustomerID) が抜けの可能性について 

### ISSUE THREAD

**Issue by manabian-** [skotani-db/openhack2023#1]
顧客別の数値を表示する想定だと思いますが、CustomerID を下記画像のように記載すべきではないでしょうか。

<img width="277" alt="image" src="https://github.com/skotani-db/openhack2023/assets/10123723/433f2abe-b425-4ea3-aa87-a8041290c24b">

対象のコードは下記です。

https://github.com/skotani-db/openhack2023/blob/a46a0aaeebe67ad650b6458cdafb0a592faef007/Openhack%20for%20Lakehouse%202023/1-1%20EDA.py#L238C1-L242C30

**Comment by skotani-db** [comment]
@manabian- 承認します。アサインしても良いでしょうか。

**Comment by manabian-** [comment]
@skotani-db 

はい。

**Comment by skotani-db** [comment]
ありがとうございます！

**Comment by skotani-db** [comment]
LGTM

**Comment by manabian-** [comment]
対応完了のため、クローズ
