### ISSUE TITLE
2-1 Generate Transaction Data にてスライドを表示できず

### ISSUE THREAD

**Issue by manabian-** [skotani-db/openhack2023#2]
cmd 5 にて、403 エラー（権限不足）で表示できまんでした。

<img width="497" alt="image" src="https://github.com/skotani-db/openhack2023/assets/10123723/1c62909a-7a64-49bc-b0a8-8fc72e2aafdb">

直接、Google スライドも表示できず。

<img width="481" alt="image" src="https://github.com/skotani-db/openhack2023/assets/10123723/5b7ba895-1bbf-49a4-8a1a-690c8591f004">

https://docs.google.com/presentation/u/0/d/1EyfnWydnePJ6g7eq6gaRp4HmDpDoiOEB6Mx_r3ff2F4/embed?slide=id.g29db854fa67_0_337&rm=minimal&pli=1

**Comment by skotani-db** [comment]
弊社のGslideが8時間おきにアクセス権がリバートされる仕組みでして、当日朝にマニュアルでアクセス権付与します
